### ISSUE TITLE
Currently not able to compile solution

### ISSUE THREAD

**Issue by jviaches** [yashaka/NSelene#36]
Downloaded your solution and tried to compile, withot any success.
Errors on declaration: using static NSelene.Selene;

Any ideas ?

**Comment by yashaka** [comment]
Hm... I have just downloaded solution, and succeeded to compile it with Mono 4.6.0 in Xamarin Studio 6.1 under Mac OS X 10.11.4.

Maybe there can be some problems under Windows and original .Net, not mono...
Maybe your version of mono or .Net is too old to support "using static"...

**Comment by jviaches** [comment]
Check it again. Solution is not compiled in Visual Studio 2015. Probably in Mono its [using static NSelene.Selene;] alowed.

Anyway it not compiling in VS. Any plans to fix it ? :)

**Comment by yashaka** [comment]
It should not be about Visual Studio, or about mono vs .NET, it's about of C# version and framework that supports it... 

"using static" is a feature of C# 6.0, that came with .NET framework 4.6/mono framework 4.6.

Seems like just your settings in Visual Studio for the NSelene project are set to target .NET framework 4.5 or lower. Try to check this and if yes, set it to target .NET 4.6. Here is the instruction: https://msdn.microsoft.com/en-us/library/bb398202.aspx

If there will be no 4.6 option available in the list, install it :) It should not be a problem...

**Comment by yashaka** [comment]
Currently I don't know what can I fix:)

I succeeded to build the project under Windows 10 VS 2015 Community on a virtual machine
I asked my friend to build it too, and he succeeded to build it on Windows 8.1 in all following VS versions:
- VS 2015 preview2
- VS 2015 Community
- VS 2013

Something weird happening on your side:) Somehow your VS do not want to support C# 6.0 features...

**Comment by yashaka** [comment]
I recommend you to check the language feature for your project by going to Properties => Build tab => Advanced button => Language Version and set C# 6.0 in case you have a lower one.
http://joxi.ru/L21vZgGF6dGK3A

**Comment by jviaches** [comment]
Perhaps i should verify on what .Net version i am running on.
By the way on my opinion it is worth to mention version of .NET you targeting on :)

**Comment by yashaka** [comment]
Actually, the targeted framework version can be found here: https://github.com/yashaka/NSelene/blob/master/NSelene/NSelene.csproj
It is 4.5

And it seems to be not the problem with version of .NET framework, but with version of C# compiler, which should be 6.0

I have already written to you what is the procedure of checking/updating the language version:

> I recommend you to check the language feature for your project by going to Properties => Build tab => Advanced button => Language Version and set C# 6.0 in case you have a lower one.
> http://joxi.ru/L21vZgGF6dGK3A

**Comment by jviaches** [comment]
I think we can close this issue
