### ISSUE TITLE
Framework is incompatible with .net Core

### ISSUE THREAD

**Issue by itrifonov** [yashaka/NSelene#37]
just create new .net Core project and install NSelene, you'll see an error.

**Comment by yashaka** [comment]
Yeah, that's weird... Need to investigate and fix it...

The current workaround would be to not create a .net Core project, but some simpler one.

**Comment by yashaka** [comment]
@itrifonov 
I have created a .Net Core MSTest project from Visual Studio for Mac. 
Added explicitly packages: NSelene, Selenium WebDriver, Selenium Support
Added a test and it worked: https://github.com/yashaka/NSeleneExamples/tree/master/NSeleneDotNetCoreMSTestProjectTest
