### ISSUE TITLE
Add support for Webdriver 3.5.2 and above

### ISSUE THREAD

**Issue by denis-platonov** [yashaka/NSelene#39]
It throws exception: "GetProperty" method is not implemented if used with any version greater than 3.5.1.
That's a real blocker for NSelene fans :) please suggest

**Comment by Legionivo** [comment]
@yashaka could you please help us with that issue? We faced with it as well.

**Comment by Magadan84** [comment]
@yashaka please, fix this issue or give some advice how to get around the issue.

**Comment by KEDelivery** [comment]
Hi, @Magadan84, 
I will try to fix the issue in the nearest week from now.

**Comment by yashaka** [comment]
@Magadan84 
Started;)

**Comment by yashaka** [comment]
should be fixed now ;)
https://www.nuget.org/packages/NSelene/0.0.0.7
