### ISSUE TITLE
add contributing section to readme

### ISSUE THREAD

**Issue by yashaka** [yashaka/NSelene#58]
Something like this: 

![image](https://user-images.githubusercontent.com/1961118/86807267-628e5d00-c082-11ea-8666-5e9524d272fe.png)

from https://github.com/yashaka/selene#contributing

You can take the latter as a template and adjust according to the dotnet and nselene context.

**Comment by davespoon** [comment]
I can do this one =)

**Comment by yashaka** [comment]
@davespoon, waiting for PR;)
