### ISSUE TITLE
cover with tests the SeleneCollection features as being Enumerable, e.g. Linq's `.First` method, etc.

### ISSUE THREAD

**Issue by yashaka** [yashaka/NSelene#59]
SeleneCollection does not have `.First` property as a shortcut for [0], but it implements Enumerable, and so all Linq methods should work. Question - will it work as expected including all "dynamic and lazy" nature of Selene? Cover all such features with tests to ensure proper behavior ;)

**Comment by OlegZarevych** [comment]
https://github.com/yashaka/NSelene/pull/66
