### ISSUE TITLE
Fluent Assertions for NSelene

### ISSUE THREAD

**Issue by yashaka** [yashaka/NSelene#65]
In PR #64 the proposal arrived to add Fluent Assertions to NSelene

Here is original idea by @wjgerritsen-0001 :

> FluentAssertions are a nice way to write assertions. The framework can easily be extended to all kinds of elements. There are extensions for HTTPResponse, etc. etc.

> My proposal is to replace the NSelene Conditions with FluentAssertion extensions. This changeset is a demostration on how it would look like. Just to discuss.

Here is example of usage:

```csharp
        [Test]
        public void HaveCssClassWithFluentAssertions()
        {
            Given.OpenedPageWithBody("<h1 class='big-title'>Hello Babe!</h1>");
            S("h1").Should().HaveNoCssClass("title");
            When.WithBody("<h1 class='big title'>Hello world!</h1>");
            S("h1").Should().HaveCssClass("title").And.HaveCssClass("big");
        }
```

here is example of implementation a corresponding assertion:

```
        public AndConstraint<SeleneElementAssertions> HaveCssClass(string cssClass, string because = "", params object[] becauseArgs)
        {
            using (var scope = new AssertionScope())
            {
                scope.AddReportable("locator", Identifier);
                Execute.Assertion
                            .BecauseOf(because, becauseArgs)
                            .Given(() => Subject.ActualWebElement.GetAttribute("class"))
                            .ForCondition(actual => actual != null && actual.Split(' ').Contains(cssClass))
                            .FailWith("Expected {locator} to contain class {0}{reason}, but found {1}.",
                                _ => cssClass, actual => actual);
            }
            return new AndConstraint<SeleneElementAssertions>(this);
        }
```

So should we go this way or not, let's discuss...

**Comment by yashaka** [comment]
First of all, this is a bit change to the API and style of the Library, which is a port of Selene from Python and Selenide from Java. One of the ideas of all set of libraries (Selene, NSelene, Selenide, SelenideJs) - is to have more or less the same core API, so it will be easier for the user to switch from one language to another depending on the project needs.  This is number one argument against...

Another thing. Conditions in Selene are not used just for assertions like in:

```csharp
S("#foo").Should(Be.Visible);
SS(".item").Should(Have.Count(10));
```

They are also used for filtering collections:

```csharp
S("#foo").Should(Be.Visible);
SS(".item").FilterBy(Be.Visible).Should(Have.Count(5));
SS(".item").FindBy(Have.CssClass("special")).Find("toggle").Click();
```

They are planned to also be used as predicates:

```csharp
if (S("#progress-bar").Matching(Be.Visible)) {
    S("#progress-bar").Should(Be.Not.Visible);
}
```

And waiting predicates too:

```csharp
if (S("#progress-bar").WaitUntil(Be.Visible)) { // waitUntil is like matching, returning true/false but with waiting until true
    S("#progress-bar").Should(Be.Not.Visible);
}
```

And potentially for "waiting while" logic when we need to check that during some time some condition is continuously matched or not (this is actual for some slow dynamic UI):

```csharp
S("#notification-error").WaitWhile(Be.Not.Visible));
```

Question, @wjgerritsen-0001, how removing conditions and adding fluent assertions can help in the latest use cases?

So far I see the condition-based implementation - more versatile and flexible. It's a classic decoupled design in accordance with the classic Command pattern. Once having condition logic in one place, without tight coupling with the "assertion context", we can reuse conditions in other scenarios as well. 

Actually we should be able to reuse conditions for Fluent Assertions too, but should we add them as part of the Cour API? I would not add them, because the API starts to be "too big". Fluent Assertions for sure can be a nice addition to NSelene, but why not implement them as extensions in a separate library, based on existing Conditions implementation? We then can mention this library in NSelene Readme, and those who find this style preferable - will be able to use it...

**Comment by wjgerritsen-0001** [comment]
Thanks for your understanding. I agree that splitting the predicate from the behavior is the thing to do in this context. I am a bit surprised that this cannot be accomplished with FluentAssertions. I looked for something similar to assertThat in Junit4 (Hamcrest), but it is quite different. Maybe we have to port that too!

So in my opinion we can close this request.

**Comment by yashaka** [comment]
Good good! Let's close the issue and the PR for now...
