### ISSUE TITLE
Consider combining conditions on distinct elements: OR, AND, XOR

### ISSUE THREAD

**Issue by wjgerritsen-0001** [yashaka/NSelene#92]
I have a UI where reports are published. Sometimes the status is immediately known, sometimes we have to hit the refresh button several times. Now I want to combine the conditions on the refresh button and the status icon on the row.

```            
            var reportRowStatusBusy = SS(".gridrow")[3].Find(By.Name("check")).Find(".fa-hourglass-half");
            var statusRefreshButton = S(".header").Find(By.Name("status-header")).Find(".ico-spin3");
            while (reportRowStatusBusy.WaitUntil(Be.Not.Visible)
/* --> */                                                             .Or(statusRefreshButton, Be.Enabled))
            {
                if (statusRefreshButton.Matching(Be.Enabled))
                {
                    Thread.Sleep(200);
                    statusRefreshButton.Click();
                }
                else
                {
                    break;
                }
            }
```

So I propose support for OR, AND, optionally XOR on conditions for various elements. 

Maybe I have missed it and it is already possible. Please comment.

**Comment by yashaka** [comment]
Condition.And and Condition.Or were added in [1.0.0-alpha05](https://github.com/yashaka/NSelene/blob/master/CHANGELOG.md#100-alpha05-released-on-20210428)

Check it;)

Yet, specifically in your case, it's not a good idea to use the while loom like in your example. Probably you need here to implement your own custom condition.. Maybe later I can provide an example:)

**Comment by wjgerritsen-0001** [comment]
Thanks for commenting. I checked it, but those are at condition level on an element or collection. I need to combine conditions on distinct elements.

I also don't like the looping, but don't think it can be omitted: we might need to hit the refresh button numerous times before we get a final status.

In our framework (based on NSelene) it now looks like:
```
            var expirationTime = DateTime.Now.AddSeconds(Data.GetTimeoutSeconds(TimeoutEnum.GenerationTimeout));
            while (DateTime.Now < expirationTime && 
                         !PublicationStatusIcon(reportName).WithTimeout(TimeoutEnum.PollTimeout).WaitForCheckIcon()) // WaitUntil
            {
                if (PublicationStatusRefreshButton.IsEnabled()) // Matching
                {
                    PublicationStatusRefreshButton.Click();
                }
                else
                {
                    break;
                }
            }
            PublicationStatusIcon(reportName).ShouldShowCheckIcon(); // Should
```

So the happy path is just waiting on the check icon. If it doesn't appear, then probably a refresh button has become active. Click that one and repeat till expiry. Else we are done. Finally check whether the check-icon is visible.

Suboptimal is that we might wait too long while the refresh button is already available, but the PollTimeout is only 500ms, so this is a limited problem.

**Comment by yashaka** [comment]
> I also don't like the looping, but don't think it can be omitted: we might need to hit the refresh button numerous times before we get a final status.

it's not about "looping is bad", it's about "explicit looping is redundant while you have an option to reuse loops inside NSelene waiting logic". If you implement your custom condition and pass it to the should on the element to be clicked - you will reuse the internal nselene's waiting loop, with corresponding benefits of reusing corresponding Configuration options like timeout and polling.

**Comment by wjgerritsen-0001** [comment]
Thanks, solved it in different way.
