### ISSUE TITLE
Add support for Selenium 4

### ISSUE THREAD

**Issue by daniilkulikov** [yashaka/NSelene#93]
After updating to Selenium version 4, we can no longer use the NSelene package in our NUnit test project, because an error appears:
System.TypeLoadException : Method 'GetDomAttribute' in type 'NSelene.SeleneElement' from assembly 'NSelene, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
For example, methods 'GetDomAttribute' and 'GetDomProperty' were added to IWebElement interface in version 4.

**Comment by Lazzaretti** [comment]
@daniilkulikov I had the same problem with version `1.0.0-alpha09`. However, I was able to fix it with version `1.0.0-alpha10`.

**Comment by yashaka** [comment]
should be fixed in 1.0.0-alpha10, thanks @Lazzaretti  for an answer!
