### ISSUE TITLE
Setting a timeout for each individual element

### ISSUE THREAD

**Issue by bughunterqa** [yashaka/NSelene#94]
Does NSelene have some logic to set the max timeout for each element individually? (as provided in Selenide: shouldBe(Condition, Duration.ofSeconds(25)))

**Comment by wjgerritsen-0001** [comment]
`webElement.With(timeout: Duration.ofSeconds(25)).Should(Be.Visible)`

**Comment by yashaka** [comment]
@wjgerritsen-0001, thanks!
@bughunterqa sorry for late response!
